### ISSUE TITLE
Can there be only 1 escrow at a time?

### ISSUE THREAD

**Issue by ally9335** [ilpr/sol_escrow#1]
Does this contract support only 1 active escrow at a time?

**Comment by ilpr** [comment]
There is no cap on simultaneous active escrows.


From: ***@***.***>
Sent: Tuesday, 22 November 2022 4:40 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [ilpr/sol_escrow] Can there be only 1 escrow at a time? (Issue #1)


Does this contract support only 1 active escrow at a time?

**Comment by ilpr** [comment]
> Does this contract support only 1 active escrow at a time?

There is no cap on simultaneous active escrows.

**Comment by ally9335** [comment]
@ilpr but each consequent escrow will overwrite the previous one

**Comment by ilpr** [comment]
> @ilpr but each consequent escrow will overwrite the previous one

No, the escrow states are stored in separate accounts. The state is written into the account in the initializing transaction and, in exchange transaction, the program checks that the correct state account has been passed in.

**Comment by ilpr** [comment]
> @ilpr but each consequent escrow will overwrite the previous one

Have you implemented the program somewhere?
